<a href="https://colab.research.google.com/github/lumagri/Python_to_Data_Science/blob/main/4_Python%20Pandas_Tratando%20e%20analisando%20dados/Organizando_DataFrames_(Sort).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = [ [ 1, 2, 3],[4, 5, 6], [7, 8, 9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
list('321')

['3', '2', '1']

In [4]:
df = pd.DataFrame(data, list('321'), list('ZYX'))
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [5]:
df.sort_index(inplace = True)
df

   Z  Y  X
1  7  8  9
2  4  5  6
3  1  2  3

In [6]:
df.sort_index(inplace = True, axis = 1)
df

   X  Y  Z
1  9  8  7
2  6  5  4
3  3  2  1

In [8]:
df.sort_values(by = 'X',inplace = True)
df

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [11]:
df.sort_values(by = ['X', 'Y'],inplace = True)
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [9]:
df.sort_values(by = '3', axis = 1, inplace = True)
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [12]:
df.sort_index()
df.sort_index(axis = 1)
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9